spring.application.name=phising-detector
server.port=8081

# Credenciales de Spring Security (Lee de variable, si no existe usa la de por defecto)
spring.security.user.name=admin
spring.security.user.password=${API_ADMIN_PASSWORD:portfolio2026}

# Configuracion de IA (Lee de variable)
ai.api.base-url=${AI_API_BASE_URL:https://api.groq.com/openai/v1}
ai.api.key=${AI_API_KEY}