spring.application.name=phising-detector
# Leemos la variable PORT del servidor, o usamos 8081 por defecto
server.port=${PORT:8081}

# Credenciales de Spring Security
spring.security.user.name=admin
spring.security.user.password=${API_ADMIN_PASSWORD:portfolio2026}

# Configuracion de IA
ai.api.base-url=${AI_API_BASE_URL:https://api.groq.com/openai/v1}
ai.api.key=${AI_API_KEY}